/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2019-08-19 12:33:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.icip.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1473314262000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar", Long.valueOf(1476254010000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("  <style type = \"css\">\r\n");
      out.write("  @import url(\"css/notice.css\")\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("  <style>\r\n");
      out.write("\r\n");
      out.write("  table.boardListBasic {\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    border-top: 1px solid #ccc;\r\n");
      out.write("    border-left: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.boardListBasic th {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-right: 1px solid #ccc;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("    border-top: 1px solid #fff;\r\n");
      out.write("    border-left: 1px solid #fff;\r\n");
      out.write("    background: #eee;\r\n");
      out.write("}\r\n");
      out.write("table.boardListBasic td {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-right: 1px solid #ccc;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  div.boardOption > ul select {\r\n");
      out.write("    width: auto;\r\n");
      out.write("    max-width: 200px\r\n");
      out.write("}\r\n");
      out.write("  input {\r\n");
      out.write("    height: inherit;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    /* -webkit-box-sizing: border-box; */\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    /* vertical-align: middle; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchbox {\r\n");
      out.write("    *width: 120px;\r\n");
      out.write("    border: 1px solid #afafaf;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #e1e1e1;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("#searchbox #search {\r\n");
      out.write("    float: left;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    padding: 0 3px;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style = \"padding-top: 10px; font-size:30px; padding-bottom:25px; color : #fde585; font-weight:bold \" >\r\n");
      out.write("공지사항\r\n");
      out.write("</div>\r\n");
      out.write("<div id = \"noticeBoard\">\r\n");
      out.write("   <div class=\"boardOption\">\r\n");
      out.write("\t\t\t\t\t<ul style = \"float: left; padding-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<li style = \"float: left; padding-bottom: 10px; padding-right : 10px; display: inline;\">\r\n");
      out.write("\t\t\t\t\t\t \t<select name=\"searchKey\" class=\"default\" title=\"선택해주세요\"  style=\"height:22px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"TITLE\" selected=\"\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"BOARD_CONTENTS\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"REG_NAME\">작성자 명</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"searchbox\" class=\"mr0\" style = \"float: left; padding-left : 20px; display: inline; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"searchTxt\" maxlength=\"100\" value=\"\" onkeyup=\"inputCheckSpecial(this)\" id=\"search\" title=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"image\" name=\"\" src=\"/images/search_btn.png\" onclick=\"javascript:searchSubmit();\" alt=\"search\">\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id = \"listBox\" style = \"display : inline-block\">\r\n");
      out.write("\t<table class=\"boardListBasic\" summary=\"게시판 리스트입니다.\">\r\n");
      out.write("\t\t\t\t\t\t<caption>게시판 리스트</caption>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"num first\">번 호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제 목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>파 일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"last\">조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"noticeView.do\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 수강신청/정정 정보 이클래스 반영시간 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2018-02-27</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">4423</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_170905182259ef57201b', '7', '2');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 학습자 업로드 자료실 관련\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2017-09-05</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">9539</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_170904164429ea1c03c0', '6', '3');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 인터넷 익스플로러 온라인강의 오류 관련\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2017-09-04</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">5623</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_1709011805497761168b', '5', '4');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 인터넷 익스플로러 사용 관련 (로그인 오류/화면 깨짐)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2017-09-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">3712</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_170825182300af520076', '4', '5');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 스마트 출석 사용 가이드 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\"> <i class=\"icon-data-color m0\"></i> </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2017-08-25</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">6787</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t공지\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_1708231658556b730001', '2', '6');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t[안내] 로그인 관련 및 질의응답 게시판 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\">2017-08-23</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"font-weight:bold;\" class=\"last\">2839</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"max-width:400px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_190211104424f8690aa6', '18', '7' );\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t [공지] 2019-1학기 수강 관련 이클래스 반영 기간 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2019-02-11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"last\">1886</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t10\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"max-width:400px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_1808081131198d7620ea', '17', '8' );\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t [공지] 2018-2학기 수강 관련 이클래스 반영 기간 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2018-08-08</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"last\">3308</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"odd-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t9\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"max-width:400px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_180801102431ab2a002f', '16', '9' );\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t [공지]시스템 작업 안내 - 8.11(토) 13시 ~ 24시\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2018-08-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"last\">228</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t8\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"textLeft\" style=\"max-width:400px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-left: 0px;\" align=\"absmiddle\" alt=\"\">\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"clip boardTitleNcontent TITLE_ORIGIN\" href=\"javascript:moveBoardView('BOAD_1807231249079c34163c', '15', '10' );\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t 2018-2학기 학부 수강신청 시범운영 안내 (7.30~8.1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"boardTitleNcontent REG_NAME\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>2018-07-23</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"last\">563</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("//글쓰기\r\n");
      out.write("function fn_write(){\r\n");
      out.write("    \r\n");
      out.write("    var form = document.getElementById(\"boardForm\");\r\n");
      out.write("    \r\n");
      out.write("    form.action = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("    form.submit();\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("//글조회\r\n");
      out.write("function fn_view(code){\r\n");
      out.write("    \r\n");
      out.write("    var form = document.getElementById(\"boardForm\");\r\n");
      out.write("    var url = \"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("   // url = url + \"?code=\" + code;\r\n");
      out.write("    \r\n");
      out.write("    form.action = url;    \r\n");
      out.write("    form.submit(); \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/icip/notice/noticeList.jsp(389,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("noticeWrite.do");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/icip/notice/noticeList.jsp(398,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("noticeView.do");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
