/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2019-08-20 00:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views.layouts.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1473314262000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/tlds/taglib.tld", Long.valueOf(1554282802000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> \r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<!-- ------------------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("   <head>\r\n");
      out.write("       <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("       <title>타 이 틀</title>\r\n");
      out.write("<!-- ------------------------------------------------------------------------------------------------------------ -->       \r\n");
      out.write("       <style type = \"text/css\">\r\n");
      out.write("        #container {width:100%; height:auto; overflow:hidden;}\r\n");
      out.write("       .content {float:left; width:50px; margin-left : 40px; margin-top:50px;}\r\n");
      out.write("      .content2 {width:100%; margin-top:50px;}\r\n");
      out.write("      \r\n");
      out.write("       div { display: block; }\r\n");
      out.write("       div.cont_tit { width : 840px; height: 33px; top: 8px;}\r\n");
      out.write("      div.cont_tit .posi {width : 840px; height: 33px; top: 9px;}\r\n");
      out.write("       ol, ul, li { list-style:none; }\r\n");
      out.write("       html, body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, del, dfn, em, img, ins, kbd, q, samp, small, strong, b, i, dl, dt, dd, ol, ul, li, fieldset, form, label, table, tbody, tfoot, thead, tr, th, td, article, aside, footer, header, nav, section {\r\n");
      out.write("       margin: 0;\r\n");
      out.write("       padding: 0; border: 0;\r\n");
      out.write("       border-radius: 0;\r\n");
      out.write("       outline:0;\r\n");
      out.write("       font-size:100%;\r\n");
      out.write("       }\r\n");
      out.write("        \r\n");
      out.write("       .posi {position:absolute; top: 46px; right: 0;}\r\n");
      out.write("      .posi a, .posi strong {display:inline-block; font-size:13px; padding:0 10px 0 15px; color:#999999; font-weight:normal;}\r\n");
      out.write("      .posi a, .posi strong {background:url(../images/common/bul_02.png) no-repeat left center;}\r\n");
      out.write("      .posi span:nth-child(1) a { padding-left:15px; padding-right:10px; background:url(/images/a_home.png) no-repeat center 2px; text-indent: -99999px;}\r\n");
      out.write("      .posi span:nth-child(1) a img {margin-top:-5px}\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("       .lnb {\r\n");
      out.write("       float:left;\r\n");
      out.write("       width:200px;\r\n");
      out.write("       margin-top:50px;\r\n");
      out.write("       }\r\n");
      out.write("       .lnb:after {\r\n");
      out.write("       content:\"\";\r\n");
      out.write("       display:block;\r\n");
      out.write("       clear:both;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("      .lnb h2 {\r\n");
      out.write("      margin: 0px 0px;\r\n");
      out.write("      padding:58px 0 57px 23px;\r\n");
      out.write("      border-bottom:1px dotted #aeaeae;\r\n");
      out.write("      font-size:28px;\r\n");
      out.write("      font-weight:bold;\r\n");
      out.write("      color:#414141;\r\n");
      out.write("      background:#fde585;\r\n");
      out.write("      }\r\n");
      out.write("       \r\n");
      out.write("       .lnb ul li a {\r\n");
      out.write("       display:block;\r\n");
      out.write("       font-size:17px;\r\n");
      out.write("       padding:17px 25px;\r\n");
      out.write("       color:#777777;\r\n");
      out.write("       font-weight: bold;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb ul li a:hover, .lnb ul li a.on {\r\n");
      out.write("       color:#fff;\r\n");
      out.write("       background:#666666 no-repeat 180px center;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb ul li a {\r\n");
      out.write("       display:block;\r\n");
      out.write("       font-size:17px;\r\n");
      out.write("       padding:17px 25px;\r\n");
      out.write("       color:#777777;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb .lnb_dep02 {\r\n");
      out.write("       padding:10px 0 20px 25px;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb .lnb_dep02 li {\r\n");
      out.write("       border:0;\r\n");
      out.write("       background:none;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb .lnb_dep02 li a {\r\n");
      out.write("       font-size:14px;\r\n");
      out.write("       padding:5px;\r\n");
      out.write("       background:none;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb .lnb_dep02 li a.on, .lnb .lnb_dep02 li a:hover {\r\n");
      out.write("       color:#fde585;\r\n");
      out.write("       background:none;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb02 .lnb_dep02 li a.on, .lnb02 .lnb_dep02 li a:hover {\r\n");
      out.write("       color:#c5a957;\r\n");
      out.write("       background:none;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       .lnb h2 {\r\n");
      out.write("       margin: 0px 0px;\r\n");
      out.write("       padding:58px 0 57px 23px;\r\n");
      out.write("       border-bottom:1px dotted #aeaeae;\r\n");
      out.write("       font-size:28px;\r\n");
      out.write("       font-weight:bold;\r\n");
      out.write("       color:#414141;\r\n");
      out.write("       background:#fde585;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("      .lnb01 h2 {background:#7c6e68;}\r\n");
      out.write("      .lnb02 h2 {background:#dccb98;}\r\n");
      out.write("      .lnb04 h2 {background:#80c0b1;}\r\n");
      out.write("      .lnb05 h2 {background:#bea086;}\r\n");
      out.write("       \r\n");
      out.write("       *, *:before, *:after {\r\n");
      out.write("       -webkit-box-sizing: border-box;\r\n");
      out.write("       -moz-box-sizing: border-box;\r\n");
      out.write("       box-sizing: border-box;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       body {\r\n");
      out.write("       font-family:NanumGothic, Dotum, Gulim, Apple SD Gothic Neo, Arial, Tahoma, sans-serif;\r\n");
      out.write("       font-size: 12px;\r\n");
      out.write("       line-height: 100%;\r\n");
      out.write("       color: #666;\r\n");
      out.write("       background-color:#ffffff;\r\n");
      out.write("       width:100%;\r\n");
      out.write("       min-width:320px;\r\n");
      out.write("       -webkit-font-smoothing: antialiased;\r\n");
      out.write("       -webkit-text-size-adjust: none;\r\n");
      out.write("       *word-break:break-all;\r\n");
      out.write("       margin:0 auto;\r\n");
      out.write("       min-width:320px;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       a, img {\r\n");
      out.write("       border:0;\r\n");
      out.write("       outline:none;\r\n");
      out.write("       selector-dummy:expression(this.hideFocus=true);\r\n");
      out.write("       padding:0;\r\n");
      out.write("       margin:0;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       a:link {\r\n");
      out.write("       color: #333333;\r\n");
      out.write("       text-decoration: none;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("      a:visited {\r\n");
      out.write("      color: #333333;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      a:hover, a:focus {\r\n");
      out.write("      color: #333333;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      a:active {\r\n");
      out.write("      color: #333333;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      hr {\r\n");
      out.write("      color : #f7f7f7;\r\n");
      out.write("      }\r\n");
      out.write("       </style>\r\n");
      out.write("       \r\n");
      out.write("       <!-- ------------------------------------------------------------------------------------------------------------ -->\r\n");
      out.write(" \r\n");
      out.write("    </head> \r\n");
      out.write("      <!-- ------------------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("    <body>\r\n");
      out.write("       <div class = \"lnb lnb03\" style = \"margin: 0 auto; width = 300px;    padding-left: 20px;\r\n");
      out.write("    width: 200px;\">\r\n");
      out.write("          <h2><img src = \"/images/1_myinformation.png\"></h2>\r\n");
      out.write("          <ul>\r\n");
      out.write("             <li><a href = \"/icip/studentinfo/viewStudentinfo.do\">학적부 조회</a></li>\r\n");
      out.write("             <div id = \"toblock\">\r\n");
      out.write("                <li><a href = \"/icip/notice/noticeList.do\">공지사항</a>\r\n");
      out.write("                   <ul class = \"lnb_dep02\" style = \"display:none;\">\r\n");
      out.write("                      <li id = \"toblock2\"><a href = \"#none\">조회</a></li>\r\n");
      out.write("                      <li id = \"toblock2\"><a href = \"#none\">등록</a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("             </div>\r\n");
      out.write("          </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class = \"content\">\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("      <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("          $('#toblock').click(function() {\r\n");
      out.write("              var state = $('#toblock2').css('display'); // state 변수에 ID가 moreMenu인 요소의 display의 속성을 '대입'\r\n");
      out.write("              if(state == 'none'){ // state가 none 상태일경우 \r\n");
      out.write("                  $('#toblock2').show(); // ID가 moreMenu인 요소를 show();\r\n");
      out.write("              }else{ // 그 외에는\r\n");
      out.write("                  $('#toblock2').hide(); // ID가 moreMenu인 요소를 hide();         \r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("      });\r\n");
      out.write("      </script>\r\n");
      out.write("    </body> \r\n");
      out.write(" </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
