/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2019-07-19 01:19:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.icip.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class joinMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1473314262000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar", Long.valueOf(1476254010000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("/WEB-INF/tlds/taglib.tld", Long.valueOf(1554282802000L));
    _jspx_dependants.put("jar:file:/D:/icipFrameWork/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/icip.app/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  /**
  * @Class Name : joinMain.jsp
  * @Description : 회원가입 화면
  * @Modification Information
  *
  *   수정일         수정자                   수정내용
  *  -------    --------    ---------------------------
  *  2019.07.17.	DGU		신규생성
  *
  * author DGU
  * since 2019.07.17
  *
  * @Copyright ⓒ 2019 Dongguk Univ., All Rights Reserved.
  */

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<META http-equiv=\"Expires\" content=\"-1\">\r\n");
      out.write("<META http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("<META http-equiv=\"Cache-Control\" content=\"No-Cache\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<link id=\"style2012\" rel=\"stylesheet\" type=\"text/css\" href=\"/css/style2012.css\" />\r\n");
      java.util.Date toDay = null;
      toDay = (java.util.Date) _jspx_page_context.getAttribute("toDay", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (toDay == null){
        toDay = new java.util.Date();
        _jspx_page_context.setAttribute("toDay", toDay, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<title>동국대학교</title>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("function infoConfirm() {//필드 자체에서 바로 처리하는 alert(컨트롤러로 넘어가지 않는다)\r\n");
      out.write("    if(document.reg_frm.id.value.length == 0) {\r\n");
      out.write("        alert(\"아이디는 필수 사항입니다.\");\r\n");
      out.write("        reg_frm.id.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.id.value.length < 4) {\r\n");
      out.write("        alert(\"아이디는 4글자 이상이어야 합니다.\");\r\n");
      out.write("        reg_frm.id.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.pw.value.length == 0) {\r\n");
      out.write("        alert(\"비밀번호는 필수 사항입니다.\");\r\n");
      out.write("        reg_frm.pw.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.pw.value != document.reg_frm.pw_check.value) {\r\n");
      out.write("        alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("        reg_frm.pw.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.name.value.length == 0) {\r\n");
      out.write("        alert(\"이름은 필수 사항입니다.\");\r\n");
      out.write("        reg_frm.name.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.id.value.length == 0) {\r\n");
      out.write("        alert(\"아아디는 필수 사항입니다.\");\r\n");
      out.write("        reg_frm.id.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if(document.reg_frm.eMail.value.length == 0) {\r\n");
      out.write("        alert(\"메일은 필수 사항입니다.\");\r\n");
      out.write("        reg_frm.eMail.focus();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    document.reg_frm.submit();//요 로직 빼는거\r\n");
      out.write("}</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#menuL ul li.mlonB\t{display:block;}\r\n");
      out.write("#contents { position:relative; z-index:9980; float:right;height:830px;width:100%;margin-left:0px; }\r\n");
      out.write(".board_list {width: 500px; margin: 0 auto;}\r\n");
      out.write(".board_list tfoot {text-align: center;}\r\n");
      out.write(".signUp_agree {text-align: center;}\r\n");
      out.write(".signUp_agree_textarea {text-align: center;}\r\n");
      out.write(".signUp_agree_textarea textarea {resize: none;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--/Header Start/-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<a href=\"\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"guide\">\r\n");
      out.write("\t<div id=\"guideL\"><span>접속 일시 : </span>");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<form action=\"joinCheck.do\" method=\"post\" name=\"reg_frm\">\r\n");
      out.write("아이디 : <input type=\"text\" name=\"id\" size\"20\"><br />\r\n");
      out.write("비밀번호 : <input type=\"password\" name=\"pw\" size\"20\"><br />\r\n");
      out.write("비밀번호 확인 : <input type=\"password\" name=\"pw_check\" size\"20\"><br />\r\n");
      out.write("이름 : <input type=\"text\" name=\"name\" size\"20\"><br />\r\n");
      out.write("메일 : <input type=\"text\" name=\"eMail\" size\"20\"><br />\r\n");
      out.write("주소 : <input type=\"text\" name=\"address\" size\"50\"><br />\r\n");
      out.write("<input type=\"button\" value=\"회원가입\" onclick=\"infoConfirm()\">\r\n");
      out.write("<input type=\"button\" value=\"취소\" onclick=\"location.href='login.do'\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/Header End/-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/jsp/icip/login/joinMain.jsp(104,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${toDay}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/icip/login/joinMain.jsp(104,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
